### ISSUE TITLE
10.9.3 codesign meltdown

### ISSUE THREAD

**Issue by mralexgray** [binaryage/asepsis#13]
all seems fine until you try to restart Finder after a `asepsisctl install`... but then..

```
5/2/14 1:20:46.096 AM com.apple.launchd.peruser.501[622]: (com.apple.Finder[46269]) Exited: Killed: 9
5/2/14 1:20:46.000 AM kernel[0]: CODE SIGNING: cs_invalid_page(0x107e19000): p=46270[Finder] final status 0x1000a00, denying page sending SIGKILL
5/2/14 1:20:46.000 AM kernel[0]: CODE SIGNING: process 46270[Finder]: rejecting invalid page at address 0x107e19000 from offset 0x1000 in file "/System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv" (cs_mtime:1399007730.0 != mtime:1399008021.0) (signed:1 validated:1 tainted:1 wpmapped:0 slid:0)
```

is this Apple putting their foot down?

**Comment by paulp** [comment]
> But luckily enough, so far no drama has been unfolding in my inbox. Maybe it is because after nuking their systems people have no way how to reach back to me ;-)

Hi! I rendered my system unbootable today (10.10.3) after uninstalling asepsis. It's entirely possible it would have recovered if I'd only rebooted and that only through my interventions did things go that far south, but through whatever combination of events I found myself in single user mode paging through "man codesign" at 80x24 until I'd figured out what needed to happen and how to do it, because it was floundering hopelessly during the boot sequence. 

(If anyone's interested, it was something like `codesign -v -s - DesktopServicesPriv.framework`.)

In some sense I'm glad it happened, because the requirement to use a named piece of software which binary-patches the operating system just so I don't have to stare at `.DS_Store`s all day is sufficiently ludicrous that I'm now full-time on what I expect to become a substantial project intended to make that notion as ridiculous as it ought to be already. And asepsis, you should be pleased to hear, becomes approximately one line of configuration once we have [suffuse](https://github.com/suffuse/suffuse). So anyway, I'm glad it happened because it makes this particular suffuse-motivating example that much stronger.

"I bricked my desktop trying to filter a single name out of a namespace." Go computers!

**Comment by paulp** [comment]
Ah, and I believe I've found what my contribution to the bricking was, via [this comment at binaryage](http://discuss.binaryage.com/t/1-5-system-log-chattiness-in-yosemite/2351/8). 

> Workaround: Delete A and create a symlink named A that points to A_.  Note that on uninstall this will brick your system if you don't restore the original framework first.

Yeah, I did the symlink thing a while ago. Brick arrived right on schedule.

**Comment by darwin** [comment]
Hi @paulp, thanks for sharing your experiences. I'm glad you were able to fix the problem on your own.
