### ISSUE TITLE
.localized file

### ISSUE THREAD

**Issue by yugenekr** [binaryage/asepsis#5]
Hi,

Thank you for your work.
Is it possible to use asepsis to removed .localized file also from Finder folders?
Would be very nice if it's possible or not difficult to implement.

Thank you,
Yuga

**Comment by davidschreiber** [comment]
+1 for this feature! Would this be possible?

**Comment by Alhadis** [comment]
+2 for this feature. Screw those stupid things.

**Comment by straxhaber** [comment]
Correct me if I'm wrong, but I don't think Finder is creating .localized folders dynamically like it does for .DS_Store. It seems like feature creep to generalize asepsis to getting rid of all existing junk, rather than focusing on preventing new junk (.DS_Store files).

**Comment by yugenekr** [comment]
@straxhaber .localized **file**, not **folders**.

**Comment by straxhaber** [comment]
Yes, you are correct @yugenekr. I was confusing .localized files for system-created folders with .localized folders for applications.

My point still stands -- asepsis _was_ useful because it took care of a recurring problem (.DS_Store file creation). .localized files only exist in system-created directories like /System, /Library, and user folder default directories. They are not automatically regenerated if you delete them, unlike .DS_Store files. If you want to delete .localized files, just go ahead and delete them manually once ("sudo find / -type f -name .localized -delete").

**Comment by yugenekr** [comment]
> They are not automatically regenerated if you delete them, unlike .DS_Store files.

Good point, @straxhaber

**Comment by bumper314** [comment]
THE SYSTEM WORKS!  Good job people =)
